### ISSUE TITLE
Dashy lxc failed to install

### ISSUE THREAD

**Issue by LocoR9** [tteck/Proxmox#2614] opened 2024-03-06 22:03 UTC
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

`yarn install v1.22.21
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-import@^2.22.1".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.4.1".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react@^7.21.5".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
warning "eslint-config-airbnb > eslint-config-airbnb-base@14.2.1" has unmet peer dependency "eslint-plugin-import@^2.22.1".
warning " > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
Done in 28.82s.
yarn run v1.22.21
$ NODE_OPTIONS=--openssl-legacy-provider vue-cli-service build
/usr/local/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
error Command failed with exit code 9.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[ERROR] in line 42: exit code 0: while executing command $STD yarn build`

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment] 2024-03-06 23:34
Looks like v2.1.2 broke things. https://github.com/Lissy93/dashy/issues

Going to set static version 2.1.1

Breaking Changes (moving to `/opt/dashy`)

**Closed as completed** 2024-03-06 23:45 UTC
Labels: 🐞  bug, ✅ Completed

**Comment by Nexow91** [comment] 2024-03-24 10:53
I have a problem with the 2.1.1 because it was set statically how do I downgrade to 2.1.0 ?

**Comment by tteck** [comment] 2024-03-24 10:55
What issues are you having with version 2.1.1?

**Comment by Nexow91** [comment] 2024-03-24 11:01
> What issues are you having with version 2.1.1?

That the authentication against the Dashy login works but no administrative rights are used. This means, for example, that it is not possible to initialize a change in the config.yml file. The config contains the admin type "admin" but I am logged in as a user and therefore cannot change anything.

**Comment by tteck** [comment] 2024-03-24 11:07
Have you followed the instructions?

![Screenshot 2024-03-24 7 03 33 AM](https://github.com/tteck/Proxmox/assets/21342670/e9038275-02d2-4b4f-9f81-8609f5447454)

**Comment by Nexow91** [comment] 2024-03-24 11:18
no access with my config (admin user type"

![image](https://github.com/tteck/Proxmox/assets/73191540/2aa36e8f-ac85-4e72-81e9-0bb9967c8694)
![image](https://github.com/tteck/Proxmox/assets/73191540/55e56a9a-84a1-4d9d-a9d7-adcad8c4853b)

**Comment by tteck** [comment] 2024-03-24 11:21
Installing to test...

**Comment by tteck** [comment] 2024-03-24 11:37
Created a new Dashy LXC
Made changes in "interactive mode", saved the changes to the disk, selected "update configuration" and hit "rebuild application"
Works as intended here


![Screenshot 2024-03-24 7 30 27 AM](https://github.com/tteck/Proxmox/assets/21342670/f4533ce3-0f0c-4894-ad06-79a7e004238d)

**Comment by Nexow91** [comment] 2024-03-24 12:06
Thanks for the feedback, did you create users in Conf.yml with the "type" "admin" as I noted in the screenshot above? Because then the execution or saving (Rebuild Application" does not work. It must also work without the interactive mode.

![image](https://github.com/tteck/Proxmox/assets/73191540/dc90905c-ec9f-4ea8-9f63-1cee15b3c952)
![image](https://github.com/tteck/Proxmox/assets/73191540/10cf328d-e9cd-4f9b-9024-1096b7fc10e8)

SHA256 
https://github.com/Lissy93/dashy/wiki/authentication/b2e548c97559860f3c3938215734be40b503de2d

**Comment by tteck** [comment] 2024-03-24 12:21
Yes, I used https://passwords-generator.org/sha256-hash-generator to generate the hashed password

**Comment by tteck** [comment] 2024-03-24 12:29
Besides, this is not a script Issue.

**Comment by tteck** [comment] 2024-03-24 12:38
You have to login after creating an admin user (top right).

**Comment by Nexow91** [comment] 2024-03-24 12:53
i have registered and it still doesn't work. i didn't say it was a script problem but that the script takes me to a newer version which according to dashy github is causing problems, hence my request for a version selection or downgrade
