### ISSUE TITLE
update-lxcs.sh broken for alpine

### ISSUE THREAD

**Issue by chwoa** [tteck/Proxmox#2366] opened 2024-01-20 00:20 UTC
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

update-lxcs.sh breaks due to not being able to find the right SSL certificates for apk update.

This has been mentioned in Alpine's gitlab: https://gitlab.alpinelinux.org/alpine/aports/-/issues/15692

Following the above, I could see how `env` would return some extra variables if run from `pct exec`, and figured that changing the script command to  `pct exec "$container" -- ash -c "unset SSL_CERT_DIR SSL_CERT_FILE && apk update && apk upgrade"` workarounds the issue, but I have not sent a pull request as I don't quite understand why pct adds those...

### Which Linux distribution are you employing?

Default Settings

### Please provide detailed steps to reproduce the issue.

Run update-lxcs.sh targeting an alpine container

**Comment by tteck** [comment] 2024-01-20 00:35
A fix has been applied for new Alpine LXC creations https://github.com/tteck/Proxmox/commit/2997b2f911aad8c564d6162182aa72f24fee4634

I'd suggest utilizing the following repositories:
```
cat <<EOF >/etc/apk/repositories
http://dl-cdn.alpinelinux.org/alpine/latest-stable/main
http://dl-cdn.alpinelinux.org/alpine/latest-stable/community
EOF
```
Execute the above code snippet in each Alpine LXC console, update/upgrade manually the first time. This will update the LXC to Alpine 3.19

**Comment by tteck** [comment] 2024-01-20 00:49
The issue is unrelated to the script and is instead related to Proxmox/Alpine, and therefore, it is considered closed.

**Closed as completed by tteck** 2024-01-20 00:49 UTC
Labels: 🧐 Not a Script Issue

**Comment by deviantintegral** [comment] 2024-01-20 17:37
This is also due to a recent change in Proxmox, and is likely a bug. It's been reported at https://bugzilla.proxmox.com/show_bug.cgi?id=5194.

At first I was a little concerned about downgrading to http, but given apk has its own signing mechanism there shouldn't be any effective reduction in package security: https://unix.stackexchange.com/questions/587447/how-can-i-check-the-validity-of-a-downloaded-alpine-linux-package
